# Generated by Django 4.0.3 on 2022-04-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('depts', models.CharField(default='none', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='exam_inv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=50)),
                ('froom', models.IntegerField(default=' ')),
                ('session', models.CharField(default='M', max_length=10)),
                ('exam_date', models.DateField(default='2022-04-16')),
            ],
        ),
        migrations.CreateModel(
            name='head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='EXAM TIMETABLE', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('roomno', models.IntegerField(primary_key=True, serialize=False)),
                ('roomcapacity', models.IntegerField()),
                ('status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('faculty_id', models.IntegerField(default='none')),
                ('faculty_status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='123', max_length=50)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.CharField(default='9:30-12:30', max_length=50)),
                ('session', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], default='M', max_length=10)),
                ('semester', models.CharField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('4-2', '4-2')], default='3-1', max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('depts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
        ),
    ]
