# Generated by Django 4.0.3 on 2022-05-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('depts', models.CharField(default='none', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='exam_inv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=50)),
                ('froom', models.IntegerField(default=' ')),
                ('session', models.CharField(default='M', max_length=10)),
                ('exam_date', models.DateField(default='2022-05-17')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='123', max_length=50)),
                ('inv_or_dc', models.CharField(default='invigilator', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='EXAM TIMETABLE', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('roomno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('session', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], default='M', max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
        ),
    ]
