# Generated by Django 4.0.3 on 2022-05-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.room'),
        ),
        migrations.AlterField(
            model_name='exam_inv',
            name='exam_date',
            field=models.DateField(default='2022-05-21'),
        ),
    ]
