# Generated by Django 4.0.3 on 2022-04-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='depts',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='email',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roomcapacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AlterField(
            model_name='exam_inv',
            name='exam_date',
            field=models.DateField(default='2022-04-24'),
        ),
    ]
