# Generated by Django 4.0.3 on 2022-04-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_exam_depts_remove_exam_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_inv',
            name='exam_date',
            field=models.DateField(default='2022-04-28'),
        ),
    ]
