# Generated by Django 4.0.3 on 2022-05-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_exam_inv_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='inv_or_dc',
            field=models.CharField(default='invigilator', max_length=11),
        ),
        migrations.AlterField(
            model_name='exam_inv',
            name='exam_date',
            field=models.DateField(default='2022-05-02'),
        ),
    ]
