# Generated by Django 4.0.3 on 2022-05-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_exam_inv_ses_a_exam_inv_ses_m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_time',
        ),
        migrations.RemoveField(
            model_name='exam_inv',
            name='ses_a',
        ),
        migrations.RemoveField(
            model_name='exam_inv',
            name='ses_m',
        ),
    ]
